---
#- name: Check the cpu has vmx option

- name: Get vmx support
  command: /usr/bin/grep -c -E '(vmx|svm)' /proc/cpuinfo
  register: result

- name: Check vmx support
  meta: end_play
  when:
    - not ansible_check_mode
    - result.stdout <= 0

- name: Install packages for kvm
  apt:
    pkg:
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - virtinst
      - cpu-checker
      - libguestfs-tools
      - libosinfo-bin
    update_cache: yes

- debug:
    var: ansible_default_ipv4.address
